import { Product, Category, StoreLocation, JobVacancy } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'yumaloq',
    label: 'Yumaloq tortlar',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4_K8bWWMOkEAdWYDDcWikyWLHYBDnF9CX0NASbCgzeZaY7w3_q1rbw8w_BIU7R0jLkLcciXT5XVRC_hjeWBzLCW4w_riysq_IPFzKrc9W7x77KSLMtfkg6Ol1NmocOo-artvnhi_L1LfYLm_7O9qTKyIXG0ZwVWg1cS_mkbc9uyvV6dYDxYTwLMOcV9cUBECj9vGA_OB3mRjxlhWsmgnndn-5OY9990sr89HCjTOW6jtieAkzh3cPgw',
    alt: 'A perfectly round, exquisite artisan cake on a minimalist white background, soft natural lighting highlighting the smooth icing.'
  },
  {
    id: 'mini',
    label: 'Mini-tortlar',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKFzoqpvNU2v5Dwv57gPjzUGvBzy0AdNcgsw3eziGfY55lz8nFGlO43mn_HxIyHzsE1B05ObT-WAiV0eysLV5eUIGbvlUdUy2qsqzwKWGfJB1Gnj8Q9c5lg5AehWEQrrBfb8g1qvM9yk0U1GygsQ6yeXm5OoPA-CXEcDn1bSlx64vLcOp2uhbi1VekoeGRkr7Bf-86VvWNkqIhPim3BtEFKtIgOY-hXnUt0K0tdy-28r6jnC7yGpmInA',
    alt: 'An array of delicate, colorful mini-cakes presented on a sleek marble surface, bright airy lighting for a premium confectionery feel.'
  },
  {
    id: 'to_gri',
    label: 'Toʻgʻri burchakli tortlar',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbIn1IxsPTP2aSFX8YyrqzuzLOo5yNhMgjcLPZNHYCzYEPvzaq86_eoy9AiP46fvOTlojRXvop1_Y8i68lLixrwb9Rmum-LwJFxnKgOhX4i-ne3K1W-6c0stGHfh11cqeBc3w-hKsm3vq1h-A0OxpqJzRRDJui3K3FZvasODrDZJOyaU6Z4yxmTCOnhlf5oHfk0VIZvba3hBV0wNtHsTPNZJtspeD2AZhn1HwlsUE-IUBgIRQigkWstw',
    alt: 'A sophisticated rectangular celebration cake decorated with fresh berries, elegant and modern styling in a well-lit bakery setting.'
  },
  {
    id: 'sirop',
    label: 'Meva siropi',
    image: '/src/assets/images/regenerated_image_1783059756141.png',
    alt: 'A premium glass bottle of vibrant pomegranate syrup, softly backlit.'
  }
];

export const PRODUCTS: Product[] = [
  // Originally from Stitch: "Сироп Гранатовый", "Сироп Кокосовый", "Торт Наполеон"
  {
    id: 'p1',
    name: 'Сироп Гранатовый',
    category: 'sirop',
    categoryLabel: 'Meva siropi',
    price: 150,
    priceStr: '150 so\'m',
    image: '/src/assets/images/regenerated_image_1783059756141.png',
    alt: 'A premium glass bottle of vibrant pomegranate syrup, softly backlit to emphasize the rich red color on a minimalist beige counter.',
    description: 'Tabiiy granat mevalaridan tayyorlangan quyuq va xushbo\'y sirop. Pishiriqlar, muzqaymoqlar va shirinliklar uchun ajoyib qo\'shimcha.',
    weight: '250 ml',
    rating: 4.8,
    ingredients: ['Tabiiy anor sharbati', 'Shakar sharbati', 'Limon kislotasi']
  },
  {
    id: 'p2',
    name: 'Сироп Кокосовый',
    category: 'sirop',
    categoryLabel: 'Meva siropi',
    price: 150,
    priceStr: '150 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCi16F1k-pBIV1LWomhBblHgllR6Vi33r9_di6vI5F8I48-lJ0BWbrlrtakXKASin1nhy3mr6o2oAIMlqqMhMs4Ye9zmtZf48b_D6wcKJPFpkp9iK3-0C3qM057nam5GESW82ITQNB34vqQ8SPwpHFT4WK3S8B07PuRwAVF-1cOFOgBqO--npiTnSS1LhIhjZ38BpAkC7M0LE0_fdYFjMjlNizzQp72CwcBWdIjyD5P39g0AmryUDKkqg',
    alt: 'A high-end coconut syrup bottle next to fresh coconut halves on a clean, light surface, creating a fresh and creamy visual mood.',
    description: 'Kokos sutidan tayyorlangan xushbo\'y, qaymoqli shirin sirop. Kofe, kokteyllar va tortlar ustiga quyish uchun mo\'ljallangan.',
    weight: '250 ml',
    rating: 4.7,
    ingredients: ['Kokos ekstrakti', 'Shakar', 'Tabiiy aromatizatorlar']
  },
  {
    id: 'p3',
    name: 'Торт Наполеон',
    category: 'yumaloq',
    categoryLabel: 'Yumaloq tortlar',
    price: 14800,
    priceStr: '14 800 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPokiqxDwPHw1TeOO0z2kLUrqHAlLiBfLqgR3js-OA3jgF1q0t591w-blg8Y3SGidlgqmSnOFymmxgP1QiRklFBcB4zK7Uae7-ZTvrHiEHTGhzpHIn4th4APF3s5pnfrek3D_geiojD9z7Og1NyOB7gu4YUhEQRvRFXkCBpk_lpWRRAfmaRijDBNeG4zdefAL1tU4FsRA3Aoo9wkLu6f4x2YacwcQSMKsulDlpkv-bq-e2GIlSYT9CDA',
    alt: 'A delicious slice of classic Napoleon cake with flaky layers and rich custard cream, beautifully plated in a bright cafe setting.',
    description: 'Bizning afsonaviy Napoleon tortimiz. Yupqa, qatlama xamirlar orasida eng nozik sariyog\'li va quyiltirilgan sutli qaymoq (krem) uyg\'unligi.',
    weight: '1200 g',
    rating: 4.9,
    ingredients: ['Oliy navli bug\'doy uni', 'Sariyog\'', 'Tuxum', 'Quyiltirilgan sut', 'Vanil']
  },
  // Extra Rich Products to explore in the dynamic catalog
  {
    id: 'p4',
    name: 'Торт Медовик Классический',
    category: 'yumaloq',
    categoryLabel: 'Yumaloq tortlar',
    price: 12500,
    priceStr: '12 500 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4_K8bWWMOkEAdWYDDcWikyWLHYBDnF9CX0NASbCgzeZaY7w3_q1rbw8w_BIU7R0jLkLcciXT5XVRC_hjeWBzLCW4w_riysq_IPFzKrc9W7x77KSLMtfkg6Ol1NmocOo-artvnhi_L1LfYLm_7O9qTKyIXG0ZwVWg1cS_mkbc9uyvV6dYDxYTwLMOcV9cUBECj9vGA_OB3mRjxlhWsmgnndn-5OY9990sr89HCjTOW6jtieAkzh3cPgw',
    alt: 'A honey cake decorated with delicate honey crumbs and natural flower details.',
    description: 'Haqiqiy tog\' asali solingan xushbo\'y, yumshoq xamirlar hamda smetanali kremning klassik birlashishi. Bolalikdagi tanish ta\'m.',
    weight: '1000 g',
    rating: 4.9,
    ingredients: ['Tabiiy asal', 'Smetana', 'Bug\'doy uni', 'Shakar', 'Sariyog\'']
  },
  {
    id: 'p5',
    name: 'Торт Красный Бархат',
    category: 'yumaloq',
    categoryLabel: 'Yumaloq tortlar',
    price: 18000,
    priceStr: '18 000 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKFzoqpvNU2v5Dwv57gPjzUGvBzy0AdNcgsw3eziGfY55lz8nFGlO43mn_HxIyHzsE1B05ObT-WAiV0eysLV5eUIGbvlUdUy2qsqzwKWGfJB1Gnj8Q9c5lg5AehWEQrrBfb8g1qvM9yk0U1GygsQ6yeXm5OoPA-CXEcDn1bSlx64vLcOp2uhbi1VekoeGRkr7Bf-86VvWNkqIhPim3BtEFKtIgOY-hXnUt0K0tdy-28r6jnC7yGpmInA',
    alt: 'A elegant Red Velvet cake with deep red sponge and soft cream cheese frosting.',
    description: 'Kakao ta\'mli mayin qizil biskvitlar hamda qaymoqli pishloq (Cream Cheese) asosidagi nozik krem birlashmasidan yaratilgan ulug\'vor tort.',
    weight: '1100 g',
    rating: 4.8,
    ingredients: ['Qaymoqli pishloq', 'Kakao', 'Sariyog\'', 'Oziq-ovqat bo\'yog\'i', 'Qaymoq']
  },
  {
    id: 'p6',
    name: 'Мини-торт Клубничный Мусс',
    category: 'mini',
    categoryLabel: 'Mini-tortlar',
    price: 8500,
    priceStr: '8 500 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKFzoqpvNU2v5Dwv57gPjzUGvBzy0AdNcgsw3eziGfY55lz8nFGlO43mn_HxIyHzsE1B05ObT-WAiV0eysLV5eUIGbvlUdUy2qsqzwKWGfJB1Gnj8Q9c5lg5AehWEQrrBfb8g1qvM9yk0U1GygsQ6yeXm5OoPA-CXEcDn1bSlx64vLcOp2uhbi1VekoeGRkr7Bf-86VvWNkqIhPim3BtEFKtIgOY-hXnUt0K0tdy-28r6jnC7yGpmInA',
    alt: 'Strawberry mousse mini cake decorated with premium chocolate flakes and fresh mint.',
    description: 'Yengil va kam kaloriyali qulupnayli muss va yangi pishgan rezavor mevalar solingan kichik bir porsiyalik baxt.',
    weight: '350 g',
    rating: 4.6,
    ingredients: ['Qulupnay piuresi', 'Kam yog\'li qaymoq', 'Jelatin', 'Biskvit']
  },
  {
    id: 'p7',
    name: 'Мини-торт Фисташковый',
    category: 'mini',
    categoryLabel: 'Mini-tortlar',
    price: 9000,
    priceStr: '9 000 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbIn1IxsPTP2aSFX8YyrqzuzLOo5yNhMgjcLPZNHYCzYEPvzaq86_eoy9AiP46fvOTlojRXvop1_Y8i68lLixrwb9Rmum-LwJFxnKgOhX4i-ne3K1W-6c0stGHfh11cqeBc3w-hKsm3vq1h-A0OxpqJzRRDJui3K3FZvasODrDZJOyaU6Z4yxmTCOnhlf5oHfk0VIZvba3hBV0wNtHsTPNZJtspeD2AZhn1HwlsUE-IUBgIRQigkWstw',
    alt: 'A pistachio premium cake slice with fresh pistachio nuts crushed on top.',
    description: 'Haqiqiy Eron pistalaridan tayyorlangan xamir hamda mayin qaymoqli krem hamohangligi. Pistali shirinliklar ishqibozlari uchun.',
    weight: '380 g',
    rating: 4.8,
    ingredients: ['Yanchilgan pista', 'Sariyog\'li krem', 'Pista pastasi', 'Mayin biskvit']
  },
  {
    id: 'p8',
    name: 'Праздничный Наполеон XLL',
    category: 'to_gri',
    categoryLabel: 'Toʻgʻri burchakli tortlar',
    price: 45000,
    priceStr: '45 000 so\'m',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbIn1IxsPTP2aSFX8YyrqzuzLOo5yNhMgjcLPZNHYCzYEPvzaq86_eoy9AiP46fvOTlojRXvop1_Y8i68lLixrwb9Rmum-LwJFxnKgOhX4i-ne3K1W-6c0stGHfh11cqeBc3w-hKsm3vq1h-A0OxpqJzRRDJui3K3FZvasODrDZJOyaU6Z4yxmTCOnhlf5oHfk0VIZvba3hBV0wNtHsTPNZJtspeD2AZhn1HwlsUE-IUBgIRQigkWstw',
    alt: 'Large party sized rectangular Napoleon cake with beautiful strawberry and powdered sugar toppings.',
    description: 'Katta oilaviy tadbirlar yoki bayramlar uchun mo\'ljallangan ulkan Napoleon torti. To\'g\'ri to\'rtburchak shaklida kesilgan va rezavor mevalar bilan bezatilgan.',
    weight: '3000 g',
    rating: 4.9,
    ingredients: ['Qatlama xamir', 'Zavarnoy krem (custard)', 'Yangi malina va qulupnaylar', 'Shakar kukuni']
  }
];

export const STORES: StoreLocation[] = [
  {
    id: 's1',
    name: 'Safia — Chilonzor filial',
    address: 'Toshkent sh., Chilonzor tumani, 2-kvartal, 15-uy',
    phone: '+998 (78) 113-40-40',
    hours: '08:00 – 22:00'
  },
  {
    id: 's2',
    name: 'Safia — Bodomzor filial',
    address: 'Toshkent sh., Yunusobod tumani, Amir Temur shoh ko\'chasi, 88A',
    phone: '+998 (78) 113-40-41',
    hours: '08:00 – 23:00'
  },
  {
    id: 's3',
    name: 'Safia — Grand Mir filial',
    address: 'Toshkent sh., Yakkasaroy tumani, Shota Rustaveli ko\'chasi, 22',
    phone: '+998 (78) 113-40-42',
    hours: '08:00 – 22:00'
  },
  {
    id: 's4',
    name: 'Safia — Sergeli filial',
    address: 'Toshkent sh., Sergeli tumani, Yangi Sergeli ko\'chasi, 4-uy',
    phone: '+998 (78) 113-40-43',
    hours: '08:00 – 21:00'
  }
];

export const VACANCIES: JobVacancy[] = [
  {
    id: 'v1',
    title: 'Konditer (Pishiriqlar ustasi)',
    department: 'Ishlab chiqarish bo\'limi',
    salary: '4 500 000 – 7 000 000 so\'m',
    experience: '1-3 yil',
    type: 'To\'liq kun (Full-time)',
    description: 'Konditerlik mahsulotlari (tort, pirojniy, pechenya) tayyorlash texnologiyasini mukammal bilish, sanitariya qoidalariga rioya qilish va ijodiy yondashuv.'
  },
  {
    id: 'v2',
    title: 'Kassir-Sotuvchi',
    department: 'Savdo bo\'limi',
    salary: '3 000 000 – 4 500 000 so\'m',
    experience: 'Tajriba talab etilmaydi (o\'rgatamiz)',
    type: 'Smenali grafik (Shift based)',
    description: 'Xaridorlar bilan muloyim muomala qilish, mahsulotlar taqdimotini o\'tkazish, kassa apparati (payme/click, terminal) bilan ishlash hamda tozalikka rioya etish.'
  },
  {
    id: 'v3',
    title: 'Kuryer (O\'z avtomobili yoki skuter bilan)',
    department: 'Logistika',
    salary: '5 000 000 – 9 000 000 so\'m (buyurtmalarga qarab)',
    experience: '6 oy',
    type: 'Moslashuvchan grafik (Flexible)',
    description: 'Tort va pishiriqlarni xavfsiz va ko\'rsatilgan vaqtda mijozlarga yetkazib berish. Toshkent shahrini yaxshi bilish va mas\'uliyatlilik talab etiladi.'
  }
];

export const TRANSLATIONS = {
  uz: {
    title: 'Safia Bakery',
    subtitle: 'Toshkent shahri',
    search: 'Qidiruv...',
    searchBtn: 'Qidirish',
    categories: 'Katalog',
    news: 'Yangiliklar',
    add: 'Qo\'shish',
    addedToCart: 'Savatga qo\'shildi!',
    all: 'Barchasi',
    home: 'Asosiy',
    cart: 'Savat',
    profile: 'Profil',
    emptyCart: 'Savat bo\'sh. Shirinliklar buyurtma qilish vaqti keldi!',
    total: 'Jami',
    checkout: 'Rasmiylashtirish',
    orderSuccess: 'Rahmat! Buyurtmangiz qabul qilindi.',
    orderSub: 'Tez orada operatorimiz siz bilan bog\'lanadi.',
    fullname: 'To\'liq ism',
    phone: 'Telefon raqam',
    address: 'Yetkazib berish manzili',
    payment: 'To\'lov turi',
    submitOrder: 'Buyurtmani tasdiqlash',
    close: 'Yopish',
    aboutUs: 'Biz haqimizda',
    stores: 'Do\'konlar',
    vacancies: 'Vakansiyalar',
    contacts: 'Kontaktlar',
    lang: 'O\'zbekcha',
    cashback: 'Safia Loyalty — Cashback',
    loyaltyCard: 'Karta raqamingiz',
    points: 'To\'plangan ballar',
    orderHistory: 'Buyurtmalar tarixi',
    aboutUsTitle: 'Safia Bakery haqida',
    aboutUsText1: 'Safia — bu oilaviy qandolat uyi bo\'lib, 20 yildan ortiq vaqtdan beri o\'zining mazali va bejirim shirinliklari bilan mijozlarni xursand qilib keladi.',
    aboutUsText2: 'Biz faqat eng yuqori sifatli va tabiiy mahsulotlardan foydalanamiz, har bir tortga o\'z sevgimizni solamiz.',
    locationTitle: 'Bizning do\'konlarimiz',
    locationSub: 'Toshkent shahri bo\'ylab filiallarimiz manzillari',
    vacancyTitle: 'Biz bilan birga ishlang!',
    vacancySub: 'Ahil jamoamizga qo\'shiling va professionallar bilan rivojlaning',
    contactTitle: 'Biz bilan aloqa',
    contactSub: 'Savol va takliflaringiz bo\'lsa, quyidagi shaklni to\'ldiring',
    feedbackSuccess: 'Xabaringiz jo\'natildi! Tez orada javob beramiz.',
    message: 'Xabar',
    send: 'Yuborish',
    rating: 'Baholash',
    weight: 'Og\'irligi',
    ingredients: 'Tarkibi',
    promotions: 'Aksiyalar',
    skillboxOffer: 'Safia ilovasida ro\'yxatdan o\'ting — Skillbox uchun 60% chegirmaga ega bo'
  },
  ru: {
    title: 'Кондитерский дом Safia',
    subtitle: 'Город Ташкент',
    search: 'Поиск...',
    searchBtn: 'Найти',
    categories: 'Каталог',
    news: 'Новинки',
    add: 'Добавить',
    addedToCart: 'Добавлено в корзину!',
    all: 'Все',
    home: 'Главная',
    cart: 'Корзина',
    profile: 'Профиль',
    emptyCart: 'В корзине пусто. Самое время заказать сладости!',
    total: 'Итого',
    checkout: 'Оформить заказ',
    orderSuccess: 'Спасибо! Ваш заказ принят.',
    orderSub: 'Скоро с вами свяжется наш оператор.',
    fullname: 'Полное имя',
    phone: 'Номер телефона',
    address: 'Адрес доставки',
    payment: 'Способ оплаты',
    submitOrder: 'Подтвердить заказ',
    close: 'Закрыть',
    aboutUs: 'О нас',
    stores: 'Магазины',
    vacancies: 'Вакансии',
    contacts: 'Контакты',
    lang: 'Русский',
    cashback: 'Safia Loyalty — Кэшбэк',
    loyaltyCard: 'Номер карты',
    points: 'Накопленные баллы',
    orderHistory: 'История заказов',
    aboutUsTitle: 'О кондитерской Safia',
    aboutUsText1: 'Safia — это семейная кондитерская, которая более 20 лет радует своих клиентов вкуснейшими и изысканными десертами.',
    aboutUsText2: 'Мы используем только высококачественные и натуральные ингредиенты, вкладывая любовь в каждый тортик.',
    locationTitle: 'Наши филиалы',
    locationSub: 'Адреса наших магазинов по всему Ташкенту',
    vacancyTitle: 'Работайте вместе с нами!',
    vacancySub: 'Присоединяйтесь к нашей дружной команде и растите вместе с нами',
    contactTitle: 'Обратная связь',
    contactSub: 'Если у вас есть вопросы или предложения, заполните форму',
    feedbackSuccess: 'Ваше сообщение отправлено! Мы скоро ответим.',
    message: 'Сообщение',
    send: 'Отправить',
    rating: 'Рейтинг',
    weight: 'Вес',
    ingredients: 'Состав',
    promotions: 'Акции',
    skillboxOffer: 'Зарегистрируйтесь в приложении Safia — получите 60% скидку на курсы Skillbox!'
  },
  en: {
    title: 'Safia Bakery',
    subtitle: 'Tashkent City',
    search: 'Search...',
    searchBtn: 'Search',
    categories: 'Catalog',
    news: 'New Arrivals',
    add: 'Add',
    addedToCart: 'Added to cart!',
    all: 'All',
    home: 'Home',
    cart: 'Cart',
    profile: 'Profile',
    emptyCart: 'Your cart is empty. Time to order some sweets!',
    total: 'Total',
    checkout: 'Checkout',
    orderSuccess: 'Thank you! Your order is placed.',
    orderSub: 'Our operator will contact you shortly.',
    fullname: 'Full Name',
    phone: 'Phone Number',
    address: 'Delivery Address',
    payment: 'Payment Method',
    submitOrder: 'Confirm Order',
    close: 'Close',
    aboutUs: 'About Us',
    stores: 'Stores',
    vacancies: 'Careers',
    contacts: 'Contacts',
    lang: 'English',
    cashback: 'Safia Loyalty — Cashback',
    loyaltyCard: 'Card Number',
    points: 'Accrued Points',
    orderHistory: 'Order History',
    aboutUsTitle: 'About Safia Bakery',
    aboutUsText1: 'Safia is a family confectionery house that has been delighting customers with delicious and refined desserts for over 20 years.',
    aboutUsText2: 'We use only the highest quality, natural ingredients, putting love into every single cake.',
    locationTitle: 'Our Branches',
    locationSub: 'Addresses of our stores across Tashkent city',
    vacancyTitle: 'Work with us!',
    vacancySub: 'Join our warm team and grow together with professionals',
    contactTitle: 'Contact Us',
    contactSub: 'If you have any questions or feedback, please fill the form',
    feedbackSuccess: 'Your message has been sent! We will reply soon.',
    message: 'Message',
    send: 'Send',
    rating: 'Rating',
    weight: 'Weight',
    ingredients: 'Ingredients',
    promotions: 'Promotions',
    skillboxOffer: 'Register in Safia app — get 60% discount for Skillbox courses!'
  }
};
